insert into Guest_Types (guest_type_name) values ('VIP');
insert into Guest_Types (guest_type_name) values ('PREMIUM PLUS');
insert into Guest_Types (guest_type_name) values ('GOLDEN');
insert into Guest_Types (guest_type_name) values ('DIAMOND');
insert into Guest_Types (guest_type_name) values ('PLATINUM');
insert into Guest_Types (guest_type_name) values ('ELITE');
insert into Guest_Types (guest_type_name) values ('EXCLUSIVE');
insert into Guest_Types (guest_type_name) values ('KING');
insert into Guest_Types (guest_type_name) values ('ROYALTY');
insert into Guest_Types (guest_type_name) values ('BORING');
insert into Guest_Types (guest_type_name) values ('STANDARD');
insert into Guest_Types (guest_type_name) values ('MINIMUM');